# Generated by Django 5.2.10 on 2026-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
